inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Include

AllCops:
  Exclude:
    - vendor/**/*
  Include:
    - .buildkite/danger/**/*
  NewCops: enable

Layout/LineLength:
  Max: 180
  Exclude:
    - fastlane/Fastfile
    - scripts/themes/download_themes.rb
    - scripts/themes/generate_themes.rb
    - scripts/themes/generate_kotlin.rb

Metrics/BlockLength:
  Exclude:
    - fastlane/Fastfile
    - scripts/themes/download_themes.rb
    - scripts/themes/generate_themes.rb
    - scripts/themes/generate_kotlin.rb
    
Metrics/MethodLength:
  Max: 30
  Exclude:
    - fastlane/Fastfile
    - scripts/themes/download_themes.rb
    - scripts/themes/generate_themes.rb
    - scripts/themes/generate_kotlin.rb

Naming/FileName:
  Exclude:
    - .buildkite/danger/Dangerfile
